name: First Workflow

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Echo phrase for job1
        run: echo "This is job1"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Echo phrase for job2
        run: echo "This is job2"
        